name: "Submit GitHub Dependency Graph"
on:
  workflow_dispatch:
  push:
  pull_request:
  
permissions: write-all

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@main    
    - name: Generate dependency graph
      uses: gradle/gradle-build-action/actions/dependency-graph-generate@main
    - name: Submit dependency graph
      uses: gradle/gradle-build-action/actions/dependency-graph-submit@main
